import pandas as pd
import os
from shutil import which
from snakemake.utils import validate, min_version
##### set minimum snakemake version #####
min_version("7.25.0")

##### load config and sample sheets #####

configfile: "config/config.yaml"

units = pd.read_table(config["units"], dtype={"sample" : str, "group" : str }).set_index("sample", drop=False)
samples = units[["sample","group"]].drop_duplicates()
if not samples['sample'].is_unique:
    raise Exception('A sample has more than one group.')

# Need this directive because both PE and SE versions of these rules produce the trimmed R1 output files.
ruleorder: trim_galore_PE > trim_galore_SE
ruleorder: seqtk_PE > seqtk_SE
ruleorder: sortmerna_PE > sortmerna_SE

rule all:
    input:
        "results/multiqc/multiqc_report.html",
        expand("results/SummarizedExperiment/{pref}.rds", pref=['SummarizedExperiment', 'sce']),
        expand("results/avg_bigwigs/{group}.unstr.bw", group=pd.unique(samples['group']))

include:
    'rules/RNAseq.smk'
include:
    'rules/qc.smk'
include:
    'rules/visualisation.smk'
